# Generated by Django 2.0.6 on 2019-03-01 16:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('subject', models.CharField(max_length=80)),
                ('hours', models.PositiveIntegerField()),
                ('workDate', models.DateField()),
                ('entryDate', models.DateTimeField(default=datetime.datetime(2019, 3, 1, 16, 40, 49, 612283, tzinfo=utc))),
                ('school', models.CharField(max_length=80)),
            ],
        ),
    ]
